name: life_view
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.18.0-238.0.dev <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_fonts: ^4.0.4
  firebase_core: ^2.14.0
  firebase_core_web: ^2.6.0
  cloud_firestore: ^4.8.2
  bloc: ^8.0.3
  flutter_bloc: ^8.0.1
  flutterfire_ui: ^0.4.0+4
  firebase_auth: ^4.6.3
  dio: ^5.2.1+1
  intl: ^0.18.0
  json_annotation: ^4.5.0
  injectable: ^2.1.2
  freezed_annotation: ^2.2.0
  retrofit: ^4.0.1
  get_it: ^7.2.0
  flutter_localizations:
    sdk: flutter
  awesome_snackbar_content: ^0.1.2  
  flutter_native_splash: ^2.2.11
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.1.2
  font_awesome_flutter: ^10.4.0
  l10n_flutter: ^1.0.7
  flutter_gen: ^5.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  bloc_test: ^9.0.3
  build_runner: ^2.1.7
  json_serializable: ^6.1.4
  freezed: ^2.3.5
  retrofit_generator: ^7.0.3
  injectable_generator: ^2.1.6

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/Nunito-Regular.ttf
        - asset: assets/fonts/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/Nunito-BlackItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Nunito-Black.ttf
          weight: 800

        - asset: assets/fonts/Nunito-ExtraBoldItalic.ttf
          style: italic
          weight: 800
        - asset: assets/fonts/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/Nunito-BoldItalic.ttf
          style: italic
          weight: 700
        - asset: assets/fonts/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Nunito-SemiBoldItalic.ttf
          style: italic
          weight: 600
        - asset: assets/fonts/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/Nunito-MediumItalic.ttf
          style: italic
          weight: 500
        - asset: assets/fonts/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/Nunito-LightItalic.ttf
          style: italic
          weight: 300
        - asset: assets/fonts/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Nunito-ExtraLightItalic.ttf
          style: italic
          weight: 200

          
flutter_native_splash:
  color: "#FFFFFF"
  image: assets/logo.png


flutter_icons:
  android: "wms"
  ios: true
  image_path: assets/logo.png
  background_color: "#FFFFFF"
  min_sdk_android: 21    
